name: Test / E2E Runner

on: push

jobs:
  chrome_e2e_php74:
    name: Chrome on PHP 8.3
    uses: ./.github/workflows/test-e2e-cypress.yml
    with:
      wpVersion: "WordPress/WordPress#6.7.2"
      phpVersion: "8.3"
    concurrency:
      group: chrome-php83
      cancel-in-progress: true